### ISSUE TITLE
您好，打开webui之后，合成语音会报错

### ISSUE THREAD

**Issue by klaylizhe** [Li-Kira/VITS_WebUI#2]
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Anaconda\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "E:\Anaconda\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Anaconda\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Anaconda\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\VITS_WebUI-Li-Kira\app.py", line 70, in tts_fn
    stn_tst = get_text(text, hps)
  File "E:\VITS_WebUI-Li-Kira\app.py", line 62, in get_text
    text_norm = text_to_sequence(text, hps.data.text_cleaners)
TypeError: text_to_sequence() missing 1 required positional argument: 'cleaner_names'

**Comment by Li-Kira** [comment]
请您试试打开`VITS_WebUI/models/`目录下的`model_info.json`文件，将其中的**model_path**修改为您的模型路径，例如`"../drive/MyDrive/Colab Notebooks/PyTorch/Vits/Yuuka.pth"`

**Comment by Li-Kira** [comment]
顺带一提，不同的VITS模型可能会有细微差异，使用本项目训练的模型只能在本项目中运行，或许您使用了其他项目中训练的模型。

**Comment by Li-Kira** [comment]
请下载新的项目替换旧的项目，我解决了一些问题并添加了新功能。

**Comment by klaylizhe** [comment]
十分感谢！我是使用的Plachtaa的项目训练的模型，刚才试过您说的方法，还是不太行，我也在自己调试。我试试您更新后的项目

**Comment by Li-Kira** [comment]
![image](https://github.com/Li-Kira/VITS_WebUI/assets/62274988/09e7ce5a-aa94-42cf-9826-3bf81002e7bc)
![image](https://github.com/Li-Kira/VITS_WebUI/assets/62274988/2ccf8f82-b205-430c-b3f1-7637063628ae)
第一次运行请将这两个地方的`MODEL_PATH`更改为您的模型路径

**Comment by klaylizhe** [comment]
合成成功了！十分感谢！非常喜欢您项目里ui的设计

**Comment by klaylizhe** [comment]
还想提醒一下大家的就是，如果训练的时候没有勾选辅助数据，合成时会提示缺少embedding，可以把model.py里的n_speaker>1改成>=1就可以使用了

**Comment by Li-Kira** [comment]
> 还想提醒一下大家的就是，如果训练的时候没有勾选辅助数据，合成时会提示缺少embedding，可以把model.py里的n_speaker>1改成>=1就可以使用了

感谢，我会加到Readme里面

**Comment by klaylizhe** [comment]
您好，似乎(我的)每个模型合成的语音都很夹子，但是其他webui合成出来的就很正常，这是因为我的模型可能和您的ui不兼容造成的嘛

**Comment by Li-Kira** [comment]
> 您好，似乎(我的)每个模型合成的语音都很夹子，但是其他webui合成出来的就很正常，这是因为我的模型可能和您的ui不兼容造成的嘛

或许您可以试试调整一下超参数，我没有试过其他模型在本项目上的表现。
